# heroku settings with postgres are commented out with 2##
spring:
  datasource:
    url: jdbc:h2:file:~\src\h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    properties:
      hibernate:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      dialect: org.hibernate.dialect.H2Dialect
      ##org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
    show-sql: false # Set true for debugging shows sql cmnds in terminal
    database-platform: org.hibernate.dialect.H2Dialect
    ##org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)
    open-in-view: false
  sql:
    init:
      platform: h2
        ##postgres
      mode: always
# Settings for heroku with postgres:
